### ISSUE TITLE
First impressions

### ISSUE THREAD

**Issue by janher** [spoiledtechie/UtopiaPimp#1]
I don't know how else to contact you appropriately, so I create this issue. I responded to your blogpost under user Janh.

I've forked the code and got it to build an run in VS 2013 (I didn't use GitHub with VS before, 2013 is on my laptop, compatible with 2013 and 2010 SP1, and has a Git client built in).

There were some troubles getting things working at first, but I managed to get the home page in my browser. I committed the changes to my fork.

For some things I didn't commit a change:
- the database files (BoomersMembership_Data.mdf, pimpTest_Data.mdf and their .ldf files) showed up as changed. I don't know why. Perhaps because I started the application, and some database contents were modified by the application?
- One warning I cannot determine what causes it (or how to fix it). My local repository is under F:\Projecten_github\UtopiaPimp:
  Unable to update auto-refresh reference 'ajaxcontroltoolkit.dll'. Cannot find assembly 'F:\Projecten_github\Documents and Settings\Scott Pio\Local Settings\Application Data\Microsoft\VisualStudio\9.0\ProjectAssemblies\nayeoep701\AjaxControlToolkit.dll'.   F:\Projecten_github\UptopiaPimp\src\Bin\ajaxcontroltoolkit.dll.refresh  src
- One warning I think can be fixed by putting things in namespaces. Though I haven't verified this, and I don't want to make such a big change without consulting you. There are more warnings like this one:
  Warning 7   The type 'admin_Errors' in 'c:\Users\janh\AppData\Local\Temp\Temporary ASP.NET Files\root\e8c15f1b\fc5b2a67\App_Web_bxqwsbmz.2.cs' conflicts with the imported type 'admin_Errors' in 'c:\Users\janh\AppData\Local\Temp\Temporary ASP.NET Files\root\e8c15f1b\fc5b2a67\App_Web_jxyeqiqx.dll'. Using the type defined in 'c:\Users\janh\AppData\Local\Temp\Temporary ASP.NET Files\root\e8c15f1b\fc5b2a67\App_Web_bxqwsbmz.2.cs'.    c:\Users\janh\AppData\Local\Temp\Temporary ASP.NET Files\root\e8c15f1b\fc5b2a67\App_Web_bxqwsbmz.2.cs   271 
- Upon first opening the home page, I get a javascript exception because "jQuery" is undefined

Could you share your views on the above remarks, and tell me how I should proceed to get the development environment set up (should I just register for an account like I would in production)?
Do you have a list of issues you want to work through?

**Comment by spoiledtechie** [comment]
When connecting to it, as you connected to the internet?  The Javascript files for the repo are referenced online.

Did you get all the way through the code and get it up and running even with these errors?

Im not too concerned about the warnings just yet.  This is old pre 2012 code.  So its going to be a small process to bring it up to speed.

On the Dbs, it is most likely occured because your using 2013 and the Dbs might have been upgraded with SQL engine.

Yes on registering the account.  Just like in production.

**Comment by janher** [comment]
I got it up and running after making changes to the code (basically the (Entitiy Framework?) code got regenerated without the proper namespaces. This was fixed by putting the namespaces in the properties for the *.dbml file.
I synced my changes to my fork here on GitHub. I don't know if you can see them without a pull request? If I need to make one, let me know.

I'll see if I can get to the bottom of the jQuery error.

**Comment by janher** [comment]
OK, I found the jQuery problem.
This is the code I got from the F12 tools, so the output from the `document.write(unescape(...))` is also shown:

``` html
<head id="ctl00_Head1">
<!-- I left out tags for readability -->
<script type="text/javascript">
    if (!window.jQuery) document.write(unescape("%3Cscript src='/mini-profiler-jquery.1.6.2.js' type='text/javascript'%3E%3C/script%3E"));
    if (!window.jQuery || !window.jQuery.tmpl) document.write(unescape("%3Cscript src='/mini-profiler-jquery.tmpl.beta1.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script src="/mini-profiler-jquery.1.6.2.js" type="text/javascript"></script>
<script src="/mini-profiler-jquery.tmpl.beta1.js" type="text/javascript"></script>
<script src="/mini-profiler-includes.js?v=1b4c97a8-4203-6a07-1a09-f7024123ea27" type="text/javascript"></script>
<script type="text/javascript">
    jQuery(function() {
        MiniProfiler.init({
            ids: ["2202a848-694e-4ae9-adc2-f1a6e9de688e"],
            path: '/',
            version: '1b4c97a8-4203-6a07-1a09-f7024123ea27',
            renderPosition: 'left',
            showTrivial: false,
            showChildrenTime: false,
            maxTracesToShow: 15,
            showControls: false
        });
    });
</script>
<!-- I left out tags for readability -->
</head>
```

I tried navigating to http://localhost:12773/mini-profiler-jquery.1.6.2.js When I do so, I get a 404 - Not Found.
Should those files be part of the source code repository on GitHub, or should they be referenced from the internet?

**Comment by janher** [comment]
OK, I know where the includes come from:
If I comment out this line in the master page, the problem goes away:

``` aspx
<%# MvcMiniProfiler.MiniProfiler.RenderIncludes() %>
```

Still don't know how to resolve it though...
From what I've found through Bing, it doesn't seem _that_ important, so I'll just leave it commented out.
