### ISSUE TITLE
Getting Access to Errors

### ISSUE THREAD

**Issue by spoiledtechie** [spoiledtechie/UtopiaPimp#4]
So there are always errors coming into pimp.  Mostly formatting errors.

@janher I need to give you the ability to see those errors, but im sort of stuck on how to do it.

Should I do an error back up, then bring it over to github so you can see it?  Whats the best way to get you access to the errors without giving you full control over pimp?

I guess I could create a new role, then allow that role to only view errors within pimp.  Thoughts?

**Comment by janher** [comment]
A new role sounds like the best idea, if you want to let me triage them.

That would only mean changing a web.config, adding the new role in de database, and adding my user to that role.
On my machine, adding a role from the UI doesn't seem to work. I wrote a script to add the role, and add user 'janhe' to that role (janhe is the user I currently use in production, though my KD doesn't really use Pimp. They want to use UpoopU for some reason).
Should I make a new user for the purpose of reviewing errors, or should I do it all as janhe?

``` SQL
  insert into [dbo].[aspnet_Roles] ([ApplicationId]
      ,[RoleId]
      ,[RoleName]
      ,[LoweredRoleName])
      output inserted.RoleId into @RoleIds(RoleId)
      values
      (
      '585D260B-D441-4910-B5DD-E96C53EBDBF0',
      NEWID(),
      'Devs',
      'devs'
      )

  insert into dbo.vw_aspnet_Roles ([ApplicationId], RoleId, RoleName, LoweredRoleName)
  select ApplicationId, r1.RoleId, RoleName, LoweredRoleName
  from dbo.aspnet_Roles r1
  where LoweredRoleName = 'devs'

  insert into [dbo].[aspnet_UsersInRoles] (UserId, RoleId)
  select UserId, r.RoleId
  FROM [dbo].[aspnet_Users]
  cross join @RoleIds r
  where LoweredUserName = 'janhe'
```

**Comment by janher** [comment]
Cannot get to the errors page as janhe. Did you put the changes in production?

**Comment by spoiledtechie** [comment]
You should now be able to see the errors page located here:

This is why I need some help.  Took me two days to get to this!  

http://utopiapimp.com/admin/admin/Errors/Errors.aspx

**Comment by spoiledtechie** [comment]
After selecting the error, what your mainly interested in, is the Submitted Data.  You just need to copy and paste that into the Input box.  Make sure it parses out all correct and from there, you should be able to trouble shoot a bit.
