### ISSUE TITLE
NullreferenceException in UtopiaParser.attachProvinceUser

### ISSUE THREAD

**Issue by janher** [spoiledtechie/UtopiaPimp#5]
A number of errors for different users occured when submitting different pages to Pimp.
I suspect the errors are triggered by the data present for those users.

I added debug code to the function, so we can get extra information when the error re-occurs.

While adding the debug code, I also saw that at one point, records (objects) from the database are selected based on hard-coded values, and then colums (properties) are read from those records (objects) without checking whether a record was found (checking the result object wasn't null).

To confirm this, I'd like to see what is available in the database could you provide me with the result from this SQL query? I hope you can connect to the production database with Sql Server Management Studio.

``` SQL
SELECT ucnp.[uid]
      ,ucnp.Column_Name
      ,ucnp.Category_ID
      ,uccnp.Category_Name
      ,ucnp.Alt
  FROM [dbo].[Utopia_Column_Name_Pull] ucnp
  FULL OUTER JOIN dbo.Utopia_Column_Catagory_Name_Pull uccnp ON ucnp.Category_ID = uccnp.Category_ID
  ORDER BY ucnp.Column_Name
```

**Comment by janher** [comment]
Oops, just saw that there are line numbers included in the stacktrace on the errors page, I am not used to that.
I've reproduced the error now. Will look further into it tomorrow.

**Comment by spoiledtechie** [comment]
Thanks!

That table is part of a set that allows the user to select as many columns as they want for the table view of the kingdom.
